import pandas as pd
from numpy import dtype

# Only the columns that should be KEPT after removing everything in the JSON
kept_columns = [
    "GENHLTH",
    "PHYSHLTH",
    "MENTHLTH",
    "POORHLTH",
    "HLTHPLN1",
    "PERSDOC2",
    "MEDCOST",
    "CHECKUP1",
    "BPHIGH4",
    "BPMEDS",
    "BLOODCHO",
    "CHOLCHK",
    "TOLDHI2",
    "CVDINFR4",
    "CVDCRHD4",
    "CVDSTRK3",
    "ASTHMA3",
    "CHCSCNCR",
    "CHCOCNCR",
    "CHCCOPD1",
    "HAVARTH3",
    "ADDEPEV2",
    "CHCKIDNY",
    "DIABETE3",
    "SEX",
    "MARITAL",
    "EDUCA",
    "VETERAN3",
    "EMPLOY1",
    "CHILDREN",
    "INCOME2",
    "INTERNET",
    "WEIGHT2",
    "HEIGHT3",
    "QLACTLM2",
    "USEEQUIP",
    "BLIND",
    "DECIDE",
    "DIFFWALK",
    "DIFFDRES",
    "DIFFALON",
    "SMOKE100",
    "SMOKDAY2",
    "USENOW3",
    "ALCDAY5",
    "AVEDRNK2",
    "DRNK3GE5",
    "MAXDRNKS",
    "FRUITJU1",
    "FRUIT1",
    "FVBEANS",
    "FVGREEN",
    "FVORANG",
    "VEGETAB1",
    "EXERANY2",
    "EXRACT11",
    "EXEROFT1",
    "EXERHMM1",
    "EXRACT21",
    "EXEROFT2",
    "EXERHMM2",
    "STRENGTH",
    "LMTJOIN3",
    "ARTHDIS2",
    "ARTHSOCL",
    "JOINPAIN",
    "SEATBELT",
    "FLUSHOT6",
    "FLSHTMY2",
    "IMFVPLAC",
    "PNEUVAC3",
    "HIVTST6",
    "PCDMDECN",
    "TRNSGNDR",
    "QSTVER",
    "QSTLANG",
    "EXACTOT1",
    "EXACTOT2",
    "_CHISPNC",
    "_RFHLTH",
    "_HCVU651",
    "_RFHYPE5",
    "_CHOLCHK",
    "_RFCHOL",
    "_MICHD",
    "_LTASTH1",
    "_CASTHM1",
    "_ASTHMS1",
    "_DRDXAR1",
    "_PRACE1",
    "_MRACE1",
    "_HISPANC",
    "_RACE",
    "_RACEG21",
    "_RACEGR3",
    "_RACE_G1",
    "_AGEG5YR",
    "_AGE65YR",
    "_AGE80",
    "_AGE_G",
    "HTIN4",
    "HTM4",
    "WTKG3",
    "_BMI5",
    "_BMI5CAT",
    "_RFBMI5",
    "_CHLDCNT",
    "_EDUCAG",
    "_INCOMG",
    "_SMOKER3",
    "_RFSMOK3",
    "DRNKANY5",
    "DROCDY3_",
    "_RFBING5",
    "_DRNKWEK",
    "_RFDRHV5",
    "FTJUDA1_",
    "FRUTDA1_",
    "BEANDAY_",
    "GRENDAY_",
    "ORNGDAY_",
    "VEGEDA1_",
    "_MISFRTN",
    "_MISVEGN",
    "_FRTRESP",
    "_VEGRESP",
    "_FRUTSUM",
    "_VEGESUM",
    "_FRTLT1",
    "_VEGLT1",
    "_FRT16",
    "_VEG23",
    "_FRUITEX",
    "_VEGETEX",
    "_TOTINDA",
    "METVL11_",
    "METVL21_",
    "MAXVO2_",
    "FC60_",
    "ACTIN11_",
    "ACTIN21_",
    "PADUR1_",
    "PADUR2_",
    "PAFREQ1_",
    "PAFREQ2_",
    "_MINAC11",
    "_MINAC21",
    "STRFREQ_",
    "PAMISS1_",
    "PAMIN11_",
    "PAMIN21_",
    "PA1MIN_",
    "PAVIG11_",
    "PAVIG21_",
    "PA1VIGM_",
    "_PACAT1",
    "_PAINDX1",
    "_PA150R2",
    "_PA300R2",
    "_PA30021",
    "_PASTRNG",
    "_PAREC1",
    "_PASTAE1",
    "_LMTACT1",
    "_LMTWRK1",
    "_LMTSCL1",
    "_RFSEAT2",
    "_RFSEAT3",
    "_FLSHOT6",
    "_PNEUMO2",
    "_AIDTST3"
  ]
# Corresponding data types (kept in the same order)
df_dtypes = [dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('O'), dtype('O'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64')]
# Descriptions for the kept columns (in the same order as above)
df_descriptions = [
    "General health", "Days physical health not good", "Days mental health not good", "Days poor health kept from usual activities",
    "Have any health care coverage", "Have one or more personal doctors or  health care provider", "Couldn’t see doctor because of cost (past 12 mo)", "Time since last routine checkup",
    "Ever told blood pressure high", "Currently taking BP medicine", "Ever had blood cholesterol checked", "Time since last cholesterol check", "Ever told cholesterol high",
    "Ever had heart attack", "Ever had angina/coronary heart disease", "Ever had stroke",
    "Ever told you had asthma", "Ever told skin cancer", "Ever told other cancers", "Ever told COPD/emphysema/chronic bronchitis", "Ever told arthritis",
    "Ever told depressive disorder", "Ever told kidney disease", "Ever told diabetes",
    "Sex", "Marital status", "Education level", "Ever active duty military", "Employment status", "Number of children in household",
    "Annual household income", "Used internet past 30 days",
    "Reported weight (pounds/kg coded)", "Reported height (ft/in or metric coded)",
    "Limited in activities due to health problems", "Needs special equipment", "Blind or serious difficulty seeing", "Difficulty concentrating/remembering",
    "Difficulty walking/climbing stairs", "Difficulty dressing/bathing", "Difficulty doing errands alone",
    "Smoked at least 100 cigarettes (lifetime)", "Current smoking frequency", "Current smokeless tobacco use",
    "Days had alcohol (past 30)", "Avg drinks on drinking days", "Binge drinking episodes (past 30)", "Max drinks one occasion (past 30)",
    "100% fruit juice intake frequency", "Fruit intake frequency", "Beans/lentils intake", "Dark green vegetables", "Orange vegetables", "Other vegetables",
    "Any leisure-time exercise past 30 days", "Primary physical activity type", "Frequency of primary activity", "Duration of primary activity",
    "Secondary physical activity type", "Frequency of secondary activity", "Duration of secondary activity", "Muscle strengthening frequency",
    "Limited due to joint symptoms (arthritis)", "Arthritis affects work", "Arthritis interferes with social activities", "Average joint pain past 30 days (0-10)",
    "Seatbelt use frequency", "Flu shot past 12 months", "Month/year of last flu shot", "Place of last flu vaccine", "Ever had pneumonia vaccine",
    "Ever tested for HIV", "Who made HIV test decision", "Transgender identity",
    "Questionnaire version", "Language of interview",
    "Other primary activity (text)", "Other secondary activity (text)",

    # Calculated variables
    "Child Hispanic origin (calculated)", "Good or better health (calc)", "Health care coverage age 18-64 (calc)", "Adults ever told high BP (calc)",
    "Cholesterol checked past 5 years (calc)", "Adults told high cholesterol (calc)", "Reported MI or CHD (calc)",
    "Ever asthma (calc)", "Current asthma (calc)", "Asthma status (calc)", "Diagnosed arthritis (calc)",
    "Preferred race", "Multiracial race", "Hispanic origin (calc)", "Race/ethnicity (calc)", "Race/ethnicity groups", "Five-level race/ethnicity", "Race for internet tables",
    "14-level age", "Age 65+ (calc)", "Imputed age collapsed", "Six-level age (calc)",

    "Height in inches (calc)", "Height in meters (calc)", "Weight in kg (calc)", "BMI (calc)", "BMI category (calc)", "Overweight/obese (calc)",
    "Number of children (calc)", "Education category (calc)", "Income category (calc)",

    "Four-level smoker status (calc)", "Current smoking (calc)",
    "Any alcohol past 30 days (calc)", "Drink-occasions per day (calc)", "Binge drinking (calc)", "Weekly drinks (calc)", "Heavy drinking (calc)",

    "Fruit juice per day (calc)", "Fruit per day (calc)", "Beans per day (calc)", "Green veg per day (calc)", "Orange veg per day (calc)", "Other veg per day (calc)",
    "Missing fruit responses", "Missing vegetable responses", "Fruit response flag", "Vegetable response flag", "Total fruit (calc)", "Total vegetables (calc)",
    "≥1 fruit/day (calc)", "≥1 vegetable/day (calc)", "Fruit >16/day flag", "Veg >23/day flag", "Fruit exclusion flag", "Vegetable exclusion flag",

    "Leisure-time PA (calc)",
    "MET value primary activity", "MET value secondary activity", "Max VO2 (calc)", "Functional capacity (calc)",
    "Intensity primary activity", "Intensity secondary activity",
    "Duration primary (min)", "Duration secondary (min)", "Frequency primary (calc)", "Frequency secondary (calc)",
    "Moderate min primary", "Moderate min secondary", "Strength frequency (calc)", "PA missing flag",
    "Total moderate min primary", "Total moderate min secondary", "Total PA minutes (calc)",
    "Vigorous min primary", "Vigorous min secondary", "Total vigorous min (calc)",
    "PA category (calc)", "Meets aerobic guideline", "≥150 min/week PA", "≥300 min/week PA", "≥300 min (2-level)", "Meets strength guideline",
    "Meets both guidelines", "Meets both (2-level)",

    "Arthritis limits activities (calc)", "Arthritis limits work (calc)", "Arthritis limits social (calc)",

    "Always/nearly always seatbelt (calc)", "Always seatbelt (calc)",
    "Flu shot past year age 65+ (calc)", "Pneumonia vaccine ever age 65+ (calc)",
    "Adults who have ever tested for HIV (calc)"
]

# Build the cleaned data dictionary
brfss_data_dict = pd.DataFrame({
    "Column": kept_columns,
    "Description": df_descriptions,
    "Data Type": df_dtypes
}).set_index("Column")

def describe_feature(column_name: str) -> str:
    """Print nice description for a column"""
    if column_name not in brfss_data_dict.index:
        return f"Column '{column_name}' not found in BRFSS dataset (cleaned version)."
    
    row = brfss_data_dict.loc[column_name]
    print(f"{column_name}\n{'=' * len(column_name)}")
    print(f"Type: {row['Data Type']}")
    print(f"Description: {row['Description']}")
    return row["Description"]

def search_description(keyword: str):
    """Search columns by keyword in description"""
    mask = brfss_data_dict["Description"].str.contains(keyword, case=False, na=False)
    return brfss_data_dict[mask]