import pandas as pd
from numpy import dtype

df_columns = ['_STATE', 'FMONTH', 'IDATE', 'IMONTH', 'IDAY', 'IYEAR', 'DISPCODE', 'SEQNO', '_PSU', 'CTELENUM', 'PVTRESD1', 'COLGHOUS', 'STATERES', 'CELLFON3', 'LADULT', 'NUMADULT', 'NUMMEN', 'NUMWOMEN', 'CTELNUM1', 'CELLFON2', 'CADULT', 'PVTRESD2', 'CCLGHOUS', 'CSTATE', 'LANDLINE', 'HHADULT', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'HLTHPLN1', 'PERSDOC2', 'MEDCOST', 'CHECKUP1', 'BPHIGH4', 'BPMEDS', 'BLOODCHO', 'CHOLCHK', 'TOLDHI2', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'ASTHNOW', 'CHCSCNCR', 'CHCOCNCR', 'CHCCOPD1', 'HAVARTH3', 'ADDEPEV2', 'CHCKIDNY', 'DIABETE3', 'DIABAGE2', 'SEX', 'MARITAL', 'EDUCA', 'RENTHOM1', 'NUMHHOL2', 'NUMPHON2', 'CPDEMO1', 'VETERAN3', 'EMPLOY1', 'CHILDREN', 'INCOME2', 'INTERNET', 'WEIGHT2', 'HEIGHT3', 'PREGNANT', 'QLACTLM2', 'USEEQUIP', 'BLIND', 'DECIDE', 'DIFFWALK', 'DIFFDRES', 'DIFFALON', 'SMOKE100', 'SMOKDAY2', 'STOPSMK2', 'LASTSMK2', 'USENOW3', 'ALCDAY5', 'AVEDRNK2', 'DRNK3GE5', 'MAXDRNKS', 'FRUITJU1', 'FRUIT1', 'FVBEANS', 'FVGREEN', 'FVORANG', 'VEGETAB1', 'EXERANY2', 'EXRACT11', 'EXEROFT1', 'EXERHMM1', 'EXRACT21', 'EXEROFT2', 'EXERHMM2', 'STRENGTH', 'LMTJOIN3', 'ARTHDIS2', 'ARTHSOCL', 'JOINPAIN', 'SEATBELT', 'FLUSHOT6', 'FLSHTMY2', 'IMFVPLAC', 'PNEUVAC3', 'HIVTST6', 'HIVTSTD3', 'WHRTST10', 'PDIABTST', 'PREDIAB1', 'INSULIN', 'BLDSUGAR', 'FEETCHK2', 'DOCTDIAB', 'CHKHEMO3', 'FEETCHK', 'EYEEXAM', 'DIABEYE', 'DIABEDU', 'PAINACT2', 'QLMENTL2', 'QLSTRES2', 'QLHLTH2', 'CAREGIV1', 'CRGVREL1', 'CRGVLNG1', 'CRGVHRS1', 'CRGVPRB1', 'CRGVPERS', 'CRGVHOUS', 'CRGVMST2', 'CRGVEXPT', 'VIDFCLT2', 'VIREDIF3', 'VIPRFVS2', 'VINOCRE2', 'VIEYEXM2', 'VIINSUR2', 'VICTRCT4', 'VIGLUMA2', 'VIMACDG2', 'CIMEMLOS', 'CDHOUSE', 'CDASSIST', 'CDHELP', 'CDSOCIAL', 'CDDISCUS', 'WTCHSALT', 'LONGWTCH', 'DRADVISE', 'ASTHMAGE', 'ASATTACK', 'ASERVIST', 'ASDRVIST', 'ASRCHKUP', 'ASACTLIM', 'ASYMPTOM', 'ASNOSLEP', 'ASTHMED3', 'ASINHALR', 'HAREHAB1', 'STREHAB1', 'CVDASPRN', 'ASPUNSAF', 'RLIVPAIN', 'RDUCHART', 'RDUCSTRK', 'ARTTODAY', 'ARTHWGT', 'ARTHEXER', 'ARTHEDU', 'TETANUS', 'HPVADVC2', 'HPVADSHT', 'SHINGLE2', 'HADMAM', 'HOWLONG', 'HADPAP2', 'LASTPAP2', 'HPVTEST', 'HPLSTTST', 'HADHYST2', 'PROFEXAM', 'LENGEXAM', 'BLDSTOOL', 'LSTBLDS3', 'HADSIGM3', 'HADSGCO1', 'LASTSIG3', 'PCPSAAD2', 'PCPSADI1', 'PCPSARE1', 'PSATEST1', 'PSATIME', 'PCPSARS1', 'PCPSADE1', 'PCDMDECN', 'SCNTMNY1', 'SCNTMEL1', 'SCNTPAID', 'SCNTWRK1', 'SCNTLPAD', 'SCNTLWK1', 'SXORIENT', 'TRNSGNDR', 'RCSGENDR', 'RCSRLTN2', 'CASTHDX2', 'CASTHNO2', 'EMTSUPRT', 'LSATISFY', 'ADPLEASR', 'ADDOWN', 'ADSLEEP', 'ADENERGY', 'ADEAT1', 'ADFAIL', 'ADTHINK', 'ADMOVE', 'MISTMNT', 'ADANXEV', 'QSTVER', 'QSTLANG', 'EXACTOT1', 'EXACTOT2', 'MSCODE', '_STSTR', '_STRWT', '_RAWRAKE', '_WT2RAKE', '_CHISPNC', '_CRACE1', '_CPRACE', '_CLLCPWT', '_DUALUSE', '_DUALCOR', '_LLCPWT', '_RFHLTH', '_HCVU651', '_RFHYPE5', '_CHOLCHK', '_RFCHOL', '_MICHD', '_LTASTH1', '_CASTHM1', '_ASTHMS1', '_DRDXAR1', '_PRACE1', '_MRACE1', '_HISPANC', '_RACE', '_RACEG21', '_RACEGR3', '_RACE_G1', '_AGEG5YR', '_AGE65YR', '_AGE80', '_AGE_G', 'HTIN4', 'HTM4', 'WTKG3', '_BMI5', '_BMI5CAT', '_RFBMI5', '_CHLDCNT', '_EDUCAG', '_INCOMG', '_SMOKER3', '_RFSMOK3', 'DRNKANY5', 'DROCDY3_', '_RFBING5', '_DRNKWEK', '_RFDRHV5', 'FTJUDA1_', 'FRUTDA1_', 'BEANDAY_', 'GRENDAY_', 'ORNGDAY_', 'VEGEDA1_', '_MISFRTN', '_MISVEGN', '_FRTRESP', '_VEGRESP', '_FRUTSUM', '_VEGESUM', '_FRTLT1', '_VEGLT1', '_FRT16', '_VEG23', '_FRUITEX', '_VEGETEX', '_TOTINDA', 'METVL11_', 'METVL21_', 'MAXVO2_', 'FC60_', 'ACTIN11_', 'ACTIN21_', 'PADUR1_', 'PADUR2_', 'PAFREQ1_', 'PAFREQ2_', '_MINAC11', '_MINAC21', 'STRFREQ_', 'PAMISS1_', 'PAMIN11_', 'PAMIN21_', 'PA1MIN_', 'PAVIG11_', 'PAVIG21_', 'PA1VIGM_', '_PACAT1', '_PAINDX1', '_PA150R2', '_PA300R2', '_PA30021', '_PASTRNG', '_PAREC1', '_PASTAE1', '_LMTACT1', '_LMTWRK1', '_LMTSCL1', '_RFSEAT2', '_RFSEAT3', '_FLSHOT6', '_PNEUMO2', '_AIDTST3']
df_dtypes = [dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64')]
df_descriptions = [
    "State FIPS Code.",
    "File Month.",
    "Interview Date.",
    "Interview Month.",
    "Interview Day.",
    "Interview Year.",
    "Final Disposition.",
    "Annual Sequence Number.",
    "Primary Sampling Unit (Equal to Annual Sequence Number).",
    "Correct Telephone Number?.",
    "Is this a private residence? [READ ONLY IF NECESSARY: “By private residence, we mean someplace like a house or apartment.”].",
    "Do you live in college housing?.",
    "Do you reside in ____(state)____?.",
    "Is this a cellular telephone? (Telephone service over the internet counts as landline service (includes Vonage, Magic Jack and other home-based phone services).)[Read only if necessary: “By cellular (or cell) telephone we mean a telephone that is mobile and usable outside of your neighborhood.”].",
    "Are you 18 years of age or older?.",
    "Number of Adults in Household.",
    "Number of Adult Men in Household.",
    "Number of Adult Women in Household.",
    "Is this (phone number) ?.",
    "Is this a cellular telephone?.",
    "Are you 18 years of age or older?.",
    "Do you live in a private residence, that is, not in a dormitory or other type of group living situation?.",
    "Do you live in college housing?.",
    "Are you a resident of [STATE]?.",
    "Do you also have a landline telephone in your home that is used to make and receive calls?.",
    "How many members of your household, including yourself, are 18 years of age or older?.",
    "Would you say that in general your health is:.",
    "Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?.",
    "Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?.",
    "During the past 30 days, for about how many days did poor physical or mental health keep you from doing your usual activities, such as self-care, work, or recreation?.",
    "Do you have any kind of health care coverage, including health insurance, prepaid plans such as HMOs, or government plans such as Medicare, or Indian Health Service?.",
    "Do you have one person you think of as your personal doctor or health care provider? (If \"No\" ask \"Is there more than one or is there no person who you think of as your personal doctor or health care provider?\".).",
    "Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?.",
    "About how long has it been since you last visited a doctor for a routine checkup? [A routine checkup is a general physical exam, not an exam for a specific injury, illness, or condition.].",
    "Have you EVER been told by a doctor, nurse or other health professional that you have high blood pressure? (If \"Yes\" and respondent is female, ask \"Was this only when you were pregnant?\".).",
    "Are you currently taking medicine for your high blood pressure?.",
    "Blood cholesterol is a fatty substance found in the blood. Have you EVER had your blood cholesterol checked?.",
    "About how long has it been since you last had your blood cholesterol checked?.",
    "Have you EVER been told by a doctor, nurse or other health professional that your blood cholesterol is high?.",
    "(Ever told) you had a heart attack, also called a myocardial infarction?.",
    "(Ever told) you had angina or coronary heart disease?.",
    "(Ever told) you had a stroke..",
    "(Ever told) you had asthma?.",
    "Do you still have asthma?.",
    "(Ever told) you had skin cancer?.",
    "(Ever told) you had any other types of cancer?.",
    "(Ever told) you have Chronic Obstructive Pulmonary Disease or COPD, emphysema or chronic bronchitis?.",
    "(Ever told) you have some form of arthritis, rheumatoid arthritis, gout, lupus, or fibromyalgia? (Arthritis diagnoses include: rheumatism, polymyalgia rheumatica; osteoarthritis (not osteporosis); tendonitis, bursitis, bunion, tennis elbow; carpal tunnel syndrome, tarsal tunnel syndrome; joint infection, etc.).",
    "(Ever told) you that you have a depressive disorder, including depression, major depression, dysthymia, or minor depression?.",
    "(Ever told) you have kidney disease? Do NOT include kidney stones, bladder infection or incontinence.(Incontinence is not being able to control urine flow.).",
    "(Ever told) you have diabetes (If \"Yes\" and respondent is female, ask \"Was this only when you were pregnant?\". If Respondent says pre-diabetes or borderline diabetes, use response code 4.).",
    "How old were you when you were told you have diabetes?.",
    "Indicate sex of respondent..",
    "Are you: (marital status).",
    "What is the highest grade or year of school you completed?.",
    "Do you own or rent your home? (Home is defined as the place where you live most of the time/the majority of the year.).",
    "Do you have more than one telephone number in your household? Do not include cell phones or numbers that are only used by a computer or fax machine..",
    "How many of these telephone numbers are residential numbers?.",
    "Do you have a cell phone for personal use? Please include cell phones used for both business and personal use.",
    "Have you ever served on active duty in the United States Armed Forces, either in the regular military or in a National Guard or military reserve unit? (Active duty does not include training for the Reserves or National Guard, but DOES include activation, for example, for the Persian Gulf War.).",
    "Are you currently…?.",
    "How many children less than 18 years of age live in your household?.",
    "Is your annual household income from all sources: (If respondent refuses at any income level, code \"Refused.\").",
    "Have you used the internet in the past 30 days?.",
    "About how much do you weigh without shoes? (If respondent answers in metrics, put a 9 in the first column)[Round fractions up.].",
    "About how tall are you without shoes? (If respondent answers in metrics, put a 9 in the first column)[Round fractions down.].",
    "To your knowledge, are you now pregnant?.",
    "Are you limited in any way in any activities because of physical, mental, or emotional problems?.",
    "Do you now have any health problem that requires you to use special equipment, such as a cane, a wheelchair, a special bed, or a special telephone? (Include occasional use or use in certain circumstances.).",
    "Are you blind or do you have serious difficulty seeing, even when wearing glasses?.",
    "Because of a physical, mental, or emotional condition, do you have serious difficulty concentrating, remembering, or making decisions?.",
    "Do you have serious difficulty walking or climbing stairs?.",
    "Do you have difficulty dressing or bathing?.",
    "Because of a physical, mental, or emotional condition, do you have difficulty doing errands alone such as visiting a doctor’s office or shopping?.",
    "Have you smoked at least 100 cigarettes in your entire life? [Note: 5 packs = 100 cigarettes].",
    "Do you now smoke cigarettes every day, some days, or not at all?.",
    "During the past 12 months, have you stopped smoking for one day or longer because you were trying to quit smoking?.",
    "How long has it been since you last smoked a cigarette, even one or two puffs?.",
    "Do you currently use chewing tobacco, snuff, or snus every day, some days, or not at all? (Snus (Swedish for snuff) is a moist smokeless tobacco, usually sold in small pouches that are placed under the lip against the gum.)[Snus (rhymes with ´goose´)].",
    "During the past 30 days, how many days per week or per month did you have at least one drink of any alcoholic beverage such as beer, wine, a malt beverage or liquor?.",
    "One drink is equivalent to a 12-ounce beer, a 5-ounce glass of wine, or a drink with one shot of liquor. During the past 30 days, on the days when you drank, about how many drinks did you drink on the average? (A 40 ounce beer would count as 3 drinks, or a cocktail drink with 2 shots would count as 2 drinks.).",
    "Considering all types of alcoholic beverages, how many times during the past 30 days did you have 5 or more drinks for men or 4 or more drinks for women on an occasion?.",
    "During the past 30 days, what is the largest number of drinks you had on any occasion?.",
    "During the past month, how many times per day, week or month did you drink 100 percent PURE fruit juices? Do not include fruit-flavored drinks with added sugar or fruit juice you made at home and added sugar to. Only include 100 percent juice.",
    "During the past month, not counting juice, how many times per day, week, or month did you eat fruit? Count fresh, frozen, or canned fruit. (Read only if necessary: “Your best guess is fine. Include apples, bananas, applesauce, oranges, grape fruit, fruit salad, watermelon, cantaloupe or musk melon, papaya, lychees, star fruit).",
    "During the past month, how many times per day, week, or month did you eat cooked or canned beans, such as refried, baked, black, garbanzo beans, beans in soup, soybeans, edamame, tofu or lentils. Do NOT include long green beans. (Read only if necessary: “Include round or oval beans or peas such as navy, pinto, split peas, cow peas, garbanzo beans, lentils, soy beans and tofu. Do NOT include long green beans such as string beans, broad or winged beans, or pole beans.”).",
    "During the past month, how many times per day, week, or month did you eat dark green vegetables for example broccoli or dark leafy greens including romaine, chard, collard greens or spinach?.",
    "During the past month, how many times per day, week, or month did you eat orange-colored vegetables such as sweet potatoes, pumpkin, winter squash, or carrots?. (Read only if needed: “Winter squash have hard, thick skins and deep yellow to orange flesh. They include acorn, buttercup, and spaghetti squash.”).",
    "Not counting what you just told me about, during the past month, about how many times per day, week, or month did you eat OTHER vegetables?. Examples of other vegetables include tomatoes, tomato juice or V-8 juice, corn, eggplant, peas, lettuce, cabbage, and white potatoes that are not fried such as baked or mashed potatoes. (Read only if needed: “Do not count vegetables you have already counted and do not include fried potatoes.”).",
    "During the past month, other than your regular job, did you participate in any physical activities or exercises such as running, calisthenics, golf, gardening, or walking for exercise?.",
    "What type of physical activity or exercise did you spend the most time doing during the past month?.",
    "How many times per week or per month did you take part in this activity during the past month?.",
    "And when you took part in this activity, for how many minutes or hours did you usually keep at it?.",
    "What other type of physical activity gave you the next most exercise during the past month?.",
    "How many times per week or per month did you take part in this activity during the past month?.",
    "And when you took part in this activity, for how many minutes or hours did you usually keep at it?.",
    "During the past month, how many times per week or per month did you do physical activities or exercises to STRENGTHEN your muscles?. [Do NOT count aerobic activities like walking, running, or bicycling. Count activities using your own body weight like yoga, sit-ups or push-ups and those using weight machines, free weights, or elastic bands.].",
    "Are you now limited in any way in any of your usual activities because of arthritis or joint symptoms?. (The preceding statement notes: Arthritis can cause symptoms like pain, aching, or stiffness in or around a joint.)",
    "Do arthritis or joint symptoms now affect whether you work, the type of work you do or the amount of work you do?. (The preceding statement notes: In this next question we are referring to work for pay.)",
    "During the past 30 days, to what extent has your arthritis or joint symptoms interfered with your normal social activities, such as going shopping, to the movies, or to religious or social gatherings?.",
    "Please think about the past 30 days, keeping in mind all of your joint pain or aching and whether or not you have taken medication. DURING THE PAST 30 DAYS, how bad was your joint pain ON AVERAGE?. [Please answer on a scale of 0 to 10 where 0 is no pain or aching and 10 is pain or aching as bad as it can be.].",
    "How often do you use seat belts when you drive or ride in a car? Would you say—.",
    "During the past 12 months, have you had either a flu shot or a flu vaccine that was sprayed in your nose?. (A new flu shot came out in 2011 that injects vaccine into the skin with a very small needle. It is called Fluzone Intradermal vaccine. This is also considered a flu shot.). (The question preamble explains: There are two ways to get the flu vaccine, one is a shot in the arm and the other is a spray, mist, or drop in the nose called FluMist™.)",
    "During what month and year did you receive your most recent flu shot injected into your arm or flu vaccine that was sprayed in your nose?.",
    "At what kind of place did you get your last flu shot/vaccine?.",
    "A pneumonia shot or pneumococcal vaccine is usually given only once or twice in a person´s lifetime and is different from the flu shot. Have you ever had a pneumonia shot?.",
    "Have you ever been tested for HIV? Do not count tests you may have had as part of a blood donation. Include testing fluid from your mouth.",
    "Not including blood donations, in what month and year was your last HIV test? (If response is before January 1985, code \"777777\".).",
    "Where did you have your last HIV test — at a private doctor or HMO office, at a counseling and testing site, in the emergency room, as an inpatient in a hospital, at a clinic, in a jail or prison, at a drug treatment facility, at home, or somewhere else?.",
    "Have you had a test for high blood sugar or diabetes within the past three years?.",
    "Have you ever been told by a doctor or other health professional that you have pre-diabetes or borderline diabetes?. (If “Yes” and respondent is female, ask: “Was this only when you were pregnant?”).",
    "Are you now taking insulin?.",
    "About how often do you check your blood for glucose or sugar? Include times when checked by a family member or friend, but do NOT include times when checked by a health professional.",
    "About how often do you check your feet for any sores or irritations? Include times when checked by a family member or friend, but do NOT include times when checked by a health professional.",
    "About how many times in the past 12 months have you seen a doctor, nurse, or other health professional for your diabetes?.",
    "A test for “A one C” measures the average level of blood sugar over the past three months. About how many times in the past 12 months has a doctor, nurse, or other health professional checked you for “A one C”?.",
    "About how many times in the past 12 months has a health professional checked your feet for any sores or irritations?.",
    "When was the last time you had an eye exam in which the pupils were dilated? This would have made you temporarily sensitive to bright light.",
    "Has a doctor ever told you that diabetes has affected your eyes or that you had retinopathy?.",
    "Have you ever taken a course or class in how to manage your diabetes yourself?.",
    "During the past 30 days, for about how many days did pain make it hard for you to do your usual activities, such as self-care, work, or recreation?.",
    "During the past 30 days, for about how may days have you felt sad, blue, or depressed?.",
    "During the past 30 days, for about how many days have you felt worried, tense, or anxious?.",
    "During the past 30 days, for about how many days have you felt very healthy and full of energy?.",
    "During the past 30 days, did you provide regular care or assistance to a friend or family member who has a health problem or disability?. (The question preamble notes: People may provide regular care or assistance to a friend or family member who has a health problem or disability.)",
    "What is his/her relationship to you? For example is he/she your (mother/daughter or father/son)?.",
    "For how long have you provided care for that person? Would you say….",
    "In an average week, how many hours do you provide care or assistance? Would you say….",
    "What is the main health problem, long-term illness, or disability that the person you care for has?.",
    "…Managing personal care such as giving medications, feeding, dressing, or bathing?.",
    "…Managing household tasks such as cleaning, managing money, or preparing meals?.",
    "Of the following support services, which one do you MOST need, that you are not currently getting?.",
    "In the next 2 years, do you expect to provide care or assistance to a friend or family member who has a health problem or disability?.",
    "How much difficulty, if any, do you have in recognizing a friend across the street? Would you say—.",
    "How much difficulty, if any, do you have reading print in newspapers, magazines, recipes, menus, or numbers on the telephone? Would you say—.",
    "When was the last time you had your eyes examined by any doctor or eye care provider?.",
    "What is the main reason you have not visited an eye care professional in the past 12 months?.",
    "When was the last time you had an eye exam in which the pupils were dilated? This would have made you temporarily sensitive to bright light.",
    "Do you have any kind of health insurance coverage for eye care?.",
    "Have you been told by an eye doctor or other health care professional that you NOW have cataracts?.",
    "Have you EVER been told by an eye doctor or other health care professional that you had glaucoma?.",
    "Have you EVER been told by an eye doctor or other health care professional that you had age-related macular degeneration?.",
    "During the past 12 months, have you experienced confusion or memory loss that is happening more often or is getting worse?.",
    "During the past 12 months, as a result of confusion or memory loss, how often have you given up day-to-day household activities or chores you used to do, such as cooking, cleaning, taking medications, driving, or paying bills?.",
    "As a result of confusion or memory loss, how often do you need assistance with these day-to-day activities?.",
    "When you need help with these day-to-day activities, how often are you able to get the help that you need?.",
    "During the past 12 months, how often has confusion or memory loss interfered with your ability to work, volunteer, or engage in social activities outside the home?.",
    "Have you or anyone else discussed your confusion or memory loss with a health care professional?.",
    "Are you currently watching or reducing your sodium or salt intake?. (The question preamble notes: Most of the sodium or salt we eat comes from processed foods and foods prepared in restaurants. Salt also can be added in cooking or at the table.)",
    "How many days, weeks, months, or years have you been watching or reducing your sodium or salt intake?.",
    "Has a doctor or other health professional ever advised you to reduce sodium or salt intake?.",
    "How old were you when you were first told by a doctor, nurse or other health professional that you had asthma?. (The question preamble notes: Previously you said you were told by a doctor, nurse, or other health professional that you had asthma.)",
    "During the past 1263 months, have you had an episode of asthma or an asthma attack?.",
    "During the past 12 months, how many times did you visit an emergency room or urgent care center because of your asthma?.",
    "During the past 12 months, how many times did you see a doctor, nurse or other health professional for urgent treatment of worsening asthma symptoms?. (The question preamble notes: If one or more visits to Q3, fill in “Besides those emergency room or urgent care center visits,”.)",
    "During the past 12 months, how many times did you see a doctor, nurse, or other health professional for a routine checkup for your asthma?.",
    "During the past 12 months, how many days were you unable to work or carry out your usual activities because of your asthma?.",
    "Symptoms of asthma include cough, wheezing, shortness of breath, chest tightness and phlegm production when you don´t have a cold or respiratory infection. During the past 30 days, how often did you have any symptoms of asthma?.",
    "During the past 30 days, how many days did symptoms of asthma make it difficult for you to stay asleep? Would you say—.",
    "During the past 30 days, how many days did you take a prescription asthma medication to PREVENT an asthma attack from occurring?.",
    "During the past 30 days, how often did you use a prescription asthma inhaler DURING AN ASTHMA ATTACK to stop it?.",
    "Following your heart attack, did you go to any kind of outpatient rehabilitation? This is sometimes called “rehab.”.",
    "Following your stroke did you go to any kind of outpatient rehabilitation? This is sometimes called “rehab.”.",
    "Do you take aspirin daily or every other day?.",
    "Do you have a health problem or condition that makes taking aspirin unsafe for you? (If \"Yes,\" ask \"Is this a stomach condition?\").",
    "Do you take aspirin to relieve pain?.",
    "Do you take aspirin to reduce the chance of a heart attack?.",
    "Do you take aspirin to reduce the chance of a stroke?.",
    "Thinking about your arthritis or joint symptoms, which of the following best describes you TODAY?. (The question preamble notes: Earlier you indicated that you had arthritis or joint symptoms.)",
    "Has a doctor or other health professional EVER suggested losing weight to help your arthritis or joint symptoms?.",
    "Has a doctor or other health professional EVER suggested physical activity or exercise to help your arthritis or joint symptoms?. (If the respondent is unclear about whether this means an increase or decrease in physical activity, this means increase.).",
    "Have you EVER taken an educational course or class to teach you how to manage problems related to your arthritis or joint symptoms?.",
    "Since 2005, have you had a tetanus shot?. (If yes, ask: “Was this Tdap, the tetanus shot that also has pertussis or whooping cough vaccine?”).",
    "Have you ever had the HPV vaccination?. (The question preamble notes: A vaccine to prevent the human papilloma virus or HPV infection is available and is called the cervical cancer or genital warts vaccine, HPV shot, [Fill: if female “GARDASIL or CERVARIX”, if male “GARDASIL”].)",
    "How many HPV shots did you receive?.",
    "Have you ever had the shingles or zoster vaccine?.",
    "A mammogram is an x-ray of each breast to look for breast cancer. Have you ever had a mammogram?.",
    "How long has it been since you had your last mammogram?.",
    "A Pap test is a test for cancer of the cervix. Have you ever had a Pap test?.",
    "How long has it been since you had your last Pap test?.",
    "An HPV test is sometimes given with the Pap test for cervical cancer screening. Have you ever had an HPV test?.",
    "How long has it been since you had your last HPV test?.",
    "Have you had a hysterectomy? (A hysterectomy is an operation to remove the uterus (womb).).",
    "A clinical breast exam is when a doctor, nurse, or other health professional feels the breast for lumps. Have you ever had a clinical breast exam?.",
    "How long has it been since your last breast exam?.",
    "A blood stool test is a test that may use a special kit at home to determine whether the stool contains blood. Have you ever had this test using a home kit?.",
    "How long has it been since you had your last blood stool test using a home kit?.",
    "Sigmoidoscopy and colonoscopy are exams in which a tube is inserted in the rectum to view the colon for signs of cancer or other health problems. Have you ever had either of these exams?.",
    "For a SIGMOIDOSCOPY, a flexible tube is inserted into the rectum to look for problems. A COLONOSCOPY is similar, but uses a longer tube, and you are usually given medication through a needle in your arm to make you sleepy and told to have someone else drive you home after the test. Was your MOST RECENT exam a sigmoidoscopy or a colonoscopy?.",
    "How long has it been since you had your last sigmoidoscopy or colonoscopy?.",
    "A Prostate-Specific Antigen test, also called a PSA test, is a blood test used to check men for prostate cancer. Has a doctor, nurse, or other health professional EVER talked with you about the advantages of the PSA test?.",
    "Has a doctor, nurse, or other health professional EVER talked with you about the disadvantages of the PSA test?.",
    "Has a doctor, nurse, or other health professional EVER recommended that you have a PSA test?.",
    "Have you EVER HAD a PSA test?.",
    "How long has it been since you had your last PSA test?.",
    "What was the MAIN reason you had this PSA test – was it …?.",
    "Which of the following best describes the decision to have the PSA test done?.",
    "Who made the decision with you? (Mark all that apply).",
    "How often in the past 12 months would you say you were worried or stressed about having enough money to pay your rent/mortgage? Would you say.",
    "How often in the past 12 months would you say you were worried or stressed about having enough money to buy nutritious meals? Would you say.",
    "At your main job or business, how are you generally paid for the work you do. Are you:.",
    "About how many hours do you work per week on all of your jobs and businesses combined?.",
    "Thinking about the last time you worked, at your main job or business, how were you generally paid for the work you do? Were you:.",
    "Thinking about the last time you worked, about how many hours did you work per week at all of your jobs and businesses combined?.",
    "Do you consider yourself to be: (We ask this question in order to better understand the health and health care needs of people with different sexual orientations.).",
    "Do you consider yourself to be transgender? (If yes, ask “Do you consider yourself to be male-to-female, female-to-male, or gender non-conforming?).",
    "Is the child a boy or a girl?.",
    "How are you related to the child?.",
    "Has a doctor, nurse or other health professional EVER said that the child has asthma?.",
    "Does the child still have asthma?.",
    "How often do you get the social and emotional support you need?.",
    "In general, how satisfied are you with your life?.",
    "Over the last 2 weeks, how many days have you had little interest or pleasure in doing things?.",
    "Over the last 2 weeks, how many days have you felt down, depressed or hopeless?.",
    "Over the last 2 weeks, how many days have you had trouble falling asleep or staying asleep or sleeping too much?.",
    "Over the last 2 weeks, how many days have you felt tired or had little energy?.",
    "Over the last 2 weeks, how many days have you had a poor appetite or eaten too much?.",
    "Over the last 2 weeks, how many days have you felt bad about yourself or that you were a failure or had let yourself or your family down?.",
    "Over the last 2 weeks, how many days have you had trouble concentrating on things, such as reading the newspaper or watching the TV?.",
    "Over the last 2 weeks, how many days have you moved or spoken so slowly that other people could have noticed? Or the opposite – being so fidgety or restless that you were moving around a lot more than usual?.",
    "Are you now taking medicine or receiving treatment from a doctor or other health professional for any type of mental health condition or emotional problem?.",
    "Has a doctor or other healthcare provider EVER told you that you had an anxiety disorder (including acute stress disorder, anxiety, generalized anxiety disorder, obsessive-compulsive disorder, panic disorder, phobia, posttraumatic stress disorder, or social anxiety disorder)?.",
    "Questionnaire Version Identifier.",
    "Language identifier.",
    "First Activity Other response description.",
    "Second Activity Other response description.",
    "Metropolitan Status Code.",
    "Sample Design Stratification Variable (A five digit number that combines the values for _STATE (first two characters), _GEOSTR (third and fourth character), and _DENSTR2 (final character).).",
    "Stratum weight (Number of records in a stratum (NRECSTR) divided by the number of records selected (NRECSEL).).",
    "Raw weighting factor used in raking (Number of adults in the household (NUMADULT, maximum of 5) divided by the imputed number of phones (_IMPNPH, maximum of 3).).",
    "Design weight used in raking (Stratum weight (_STRWT) multiplied by the raw weighting factor (_RAWRAKE).).",
    "Child Hispanic, Latino/a, or Spanish origin calculated variable.",
    "Child multiracial race categorization.",
    "Preferred Child Race Categories.",
    "Final child weight: Land-line and Cell-Phone data (Raking derived weight).",
    "Dual Phone Use Categories.",
    "Dual phone use correction factor.",
    "Final weight assigned to each respondent: Land-line and cell-phone data (Raking derived weight).",
    "Adults with good or better health.",
    "Respondents aged 18-64 who have any form of health care coverage.",
    "Adults who have been told they have high blood pressure by a doctor, nurse, or other health professional.",
    "Cholesterol check within past five years.",
    "Adults who have had their cholesterol checked and have been told by a doctor, nurse, or other health professional that it was high.",
    "Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI).",
    "Adults who have ever been told they have asthma.",
    "Adults who have been told they currently have asthma.",
    "Computed asthma status.",
    "Respondents who have had a doctor diagnose them as having some form of arthritis.",
    "Preferred race category.",
    "Calculated multiracial race categorization.",
    "Hispanic, Latino/a, or Spanish origin calculated variable.",
    "Race/ethnicity categories.",
    "White non-Hispanic race group.",
    "Five-level race/ethnicity category.",
    "Race groups used for internet prevalence tables.",
    "Fourteen-level age category.",
    "Two-level age category.",
    "Imputed Age value collapsed above 80.",
    "Six-level imputed age category.",
    "Reported height in inches.",
    "Reported height in meters.",
    "Reported weight in kilograms.",
    "Body Mass Index (BMI).",
    "Four-categories of Body Mass Index (BMI).",
    "Adults who have a body mass index greater than 25.00 (Overweight or Obese).",
    "Number of children in household.",
    "Level of education completed.",
    "Income categories.",
    "Four-level smoker status: Everyday smoker, Someday smoker, Former smoker, Non-smoker.",
    "Adults who are current smokers.",
    "Adults who reported having had at least one drink of alcohol in the past 30 days.",
    "Drink-occasions-per-day.",
    "Binge drinkers (males having five or more drinks on one occasion, females having four or more drinks on one occasion).",
    "Calculated total number of alcoholic beverages consumed per week.",
    "Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week).",
    "Fruit juice intake in times per day.",
    "Fruit intake in times per day.",
    "Bean intake in times per day.",
    "Dark green vegetable intake in times per day.",
    "Orange-colored vegetable intake in times per day.",
    "Other vegetable intake in times per day.",
    "The number of missing fruit responses.",
    "The number of missing vegetable responses.",
    "Missing any fruit responses.",
    "Missing any vegetable responses.",
    "Total fruits consumed per day.",
    "Total vegetables consumed per day.",
    "Consume Fruit 1 or more times per day.",
    "Consume Vegetables 1 or more times per day.",
    "Reported consuming Fruit >16 per day.",
    "Reported consuming Vegetables >23 per day.",
    "Fruit Exclusion from analyses.",
    "Vegetable Exclusion from analyses.",
    "Adults who reported doing physical activity or exercise during the past 30 days other than their regular job.",
    "Activity MET Value for First Activity.",
    "Activity MET Value for Second Activity.",
    "Estimated Age-Gender Specific Maximum Oxygen Consumption.",
    "Estimated Functional Capacity.",
    "Estimated Activity Intensity for First Activity.",
    "Estimated Activity Intensity for Second Activity.",
    "Minutes of First Activity.",
    "Minutes of Second Activity.",
    "Physical Activity Frequency per Week for First Activity.",
    "Physical Activity Frequency per Week for Second Activity.",
    "Minutes of Physical Activity per week for First Activity.",
    "Minutes of Physical Activity per week for Second Activity.",
    "Strength Activity Frequency per Week.",
    "Missing Physical Activity Data.",
    "Minutes of Physical Activity per week for First Activity.",
    "Minutes of Physical Activity per week for Second Activity.",
    "Minutes of total Physical Activity per week.",
    "Minutes of Vigorous Physical Activity per week for First Activity.",
    "Minutes of Vigorous Physical Activity per week for Second Activity.",
    "Minutes of total Vigorous Physical Activity per week.",
    "Physical Activity Categories.",
    "Physical Activity Index.",
    "Adults that participated in 150 minutes (or vigorous equivalent minutes) of physical activity per week.",
    "Adults that participated in 300 minutes (or vigorous equivalent minutes) of physical activity per week.",
    "Adults that participated in 300 minutes (or vigorous equivalent minutes) of physical activity per week (2-levels).",
    "Muscle Strengthening Recommendation.",
    "Aerobic and Strengthening Guideline.",
    "Aerobic and Strengthening (2-level).",
    "Limited usual activities.",
    "Limited work activities.",
    "Limited social activities.",
    "Always or Nearly Always Wear Seat Belts Calculated Variable.",
    "Always Wear Seat Belts Calculated Variable.",
    "Adults aged 65+ who have had a flu shot within the past year.",
    "Adults aged 65+ who have ever had a pneumonia vaccination.",
    "Adults who have ever been tested for HIV."
]
brfss_data_dict = pd.DataFrame({
    "Column": df_columns,
    "Description": df_descriptions,
    "Data Type": df_dtypes
}).set_index("Column")

def describe_feature(column_name: str) -> str:
    """Print nice description for a column"""
    if column_name not in brfss_data_dict.index:
        return f"Column '{column_name}' not found in BRFSS 2025 dataset."
    
    row = brfss_data_dict.loc[column_name]
    print(f"{column_name}\n{'=' * len(column_name)}")
    print(f"Type: {row['DataType']}")
    print(f"Description: {row['Description']}")
    return row['Description']

def search_description(keyword: str):
    """Search columns by keyword in description"""
    mask = brfss_data_dict["Description"].str.contains(keyword, case=False, na=False)
    return brfss_data_dict[mask]